name: flutter_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.14.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
